# Generated by Django 6.0.4 on 2026-04-17 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('no_nomina', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('puesto', models.CharField(max_length=255)),
                ('horario_lv', models.CharField(max_length=100)),
                ('horario_s', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IncidenceCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('abreviatura', models.CharField(max_length=10)),
                ('aplica_bono_mensual', models.BooleanField(default=False)),
                ('aplica_bono_semanal', models.BooleanField(default=False)),
                ('aplica_incentivo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraHourBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_deuda', models.DecimalField(decimal_places=2, max_digits=5)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_hours', to='payroll.employee')),
            ],
        ),
        migrations.CreateModel(
            name='IncidenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('semana_num', models.IntegerField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidences', to='payroll.employee')),
                ('tipo_incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.incidencecatalog')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('abono_semanal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagos_realizados', models.IntegerField(default=0)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='payroll.employee')),
            ],
        ),
    ]
