# Generated by Django 6.0.4 on 2026-04-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_incidencerecord_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='horario_s',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
