# Generated by Django 6.0.4 on 2026-04-20 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_employee_horario_s'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_range', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='horario_lv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_lv', to='payroll.schedule'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='horario_s',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_s', to='payroll.schedule'),
        ),
    ]
