# Generated by Django 6.0.4 on 2026-04-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_schedule_alter_employee_horario_lv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='fecha_ingreso',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
