# Generated by Django 6.0.4 on 2026-04-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_employee_fecha_ingreso_employee_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_num', models.IntegerField(db_index=True)),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
                ('empleado_no_nomina', models.CharField(max_length=50)),
                ('empleado_nombre', models.CharField(max_length=255)),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desglose', models.JSONField()),
            ],
            options={
                'ordering': ['-fecha_cierre'],
            },
        ),
    ]
