# Generated by Django 6.0.4 on 2026-04-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_payroll_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='vacaciones_historicas_disfrutadas',
            field=models.IntegerField(default=0),
        ),
    ]
