# Generated by Django 6.0.4 on 2026-04-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_employee_vacaciones_historicas_disfrutadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='motivo_baja',
            field=models.TextField(blank=True, null=True),
        ),
    ]
