# Generated by Django 6.0.4 on 2026-04-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_employee_fecha_baja_employee_motivo_baja'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
    ]
