# Generated by Django 6.0.4 on 2026-05-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_create_rbac_groups'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('empleado',), name='unique_active_loan_per_employee'),
        ),
    ]
