# Generated by Django 6.0.4 on 2026-05-02 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_loan_unique_active_loan_per_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsnapshot',
            name='iso_year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='PayrollClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_year', models.IntegerField()),
                ('semana_num', models.IntegerField()),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('total_employees', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='CLOSED', max_length=20)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-iso_year', '-semana_num'],
            },
        ),
        migrations.AddField(
            model_name='payrollsnapshot',
            name='closure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='payroll.payrollclosure'),
        ),
        migrations.AddConstraint(
            model_name='payrollclosure',
            constraint=models.UniqueConstraint(fields=('iso_year', 'semana_num'), name='unique_payroll_closure_iso_year_week'),
        ),
    ]
