# Generated by Django 6.0.4 on 2026-05-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_payrollsnapshot_iso_year_payrollclosure_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payrollsnapshot',
            constraint=models.UniqueConstraint(fields=('closure', 'empleado_no_nomina'), name='unique_payroll_snapshot_closure_employee'),
        ),
    ]
